### ISSUE TITLE
Can not build on macOS with swift 3.0.2

### ISSUE THREAD

**Issue by zloidemon** [tris-foundation/tarantool#1]
```
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

```
tarantool/Package.swift:21:5: error: argument 'products' must precede argument 'targets'
    products: [
    ^
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
error: invalid manifest format
```

**Comment by tonyfreeman** [comment]
Some modules were updated to the new product API, so they won't compile with stable Swift 3 release. Please use the latest [Swift Development Snapshot](https://swift.org/download/#snapshots).

You may also use trisdocker/universe docker image, which should work for all our modules.

**Comment by zloidemon** [comment]
Latest snapshot from the site, tested on ubuntu 16.04:

```
Swift version 3.1-dev (LLVM 03606c6a3f, Clang f4873e0e90, Swift 74dcb489e6)
Target: x86_64-unknown-linux-gnu
```

It looks like missing with paths, i see files in /home/vg/Devel/Swift/current/usr/include but **CFLAGS="/path/to" swift build** doesn't solve issue. 
```
Compile Swift Module 'Socket' (5 sources)
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "CoreFoundation.h"
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:10: note: in file included from /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CoreFoundation.h:60:
#include <CoreFoundation/CFBase.h>
         ^
/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/lib/swift/CoreFoundation/CFBase.h:72:10: error: 'Block.h' file not found
#include <Block.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
<unknown>:0: error: build had 2 command failures
error: exit(1): /home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/bin/swift-build-tool -f /home/vg/Tarantool/Swift/tarantool/.build/debug.yaml
```

**Comment by tonyfreeman** [comment]
seems like it miss the libblocksruntime-dev, i would also recommend you to install the following development dependencies the https://github.com/apple/swift readme:
```bash
sudo apt-get install git cmake ninja-build clang python uuid-dev libicu-dev icu-devtools libbsd-dev libedit-dev libxml2-dev libsqlite3-dev swig libpython-dev libncurses5-dev pkg-config libblocksruntime-dev libcurl4-openssl-dev autoconf libtool systemtap-sdt-dev
```

**Comment by tonyfreeman** [comment]
all you need to setup your environment:
1. the dependencies listed in the previous comment
2. export Swift path
```bash
export PATH=/home/vg/Devel/Swift/swift-DEVELOPMENT-SNAPSHOT-2017-01-28-a-ubuntu16.04/usr/bin:$PATH
```

**Comment by tonyfreeman** [comment]
Well, i've just checked both 27 and 28 have a bug https://bugs.swift.org/browse/SR-3771
Somehow i was using older docker image, sorry for misleading you.

This one should work:
https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2017-01-24-a/swift-DEVELOPMENT-SNAPSHOT-2017-01-24-a-osx.pkg

We're working on automated CI to avoid this in the future.

**Comment by tonyfreeman** [comment]
Oh, but 24 doesn't support product API for C targets, so you need to specify 0.3.6
```swift
 .Package(url: "https://github.com/tris-foundation/tarantool.git", Version(0,3,6))
```
then 
```bash
rm Package.pins
swift package reset
swift build
```

**Comment by tonyfreeman** [comment]
Just notifying, i updated my answer with workaround for the latest snapshot. 
Feel free to reopen if you still have build errors.
